"""Policy-emission target.

Compile a cluster into a Cedar or OPA Rego rule that downstream
governance systems can ingest. The emitted code is a *machine
artifact* — per AIsafePy design principle 7, developers don't author
Cedar / Rego by hand. The runtime path uses the Python
:class:`aisafepy.core.policies.PolicyDocument` representation; this
target produces serialized DSL only for governance integrations
(OPA, AWS Verified Permissions, etc.).
"""

from __future__ import annotations

from dataclasses import dataclass

from aisafepy.adapt.cluster import Cluster
from aisafepy.adapt.compile import CompiledArtifact


@dataclass
class _PolicyTarget:
    dsl: str = "cedar"
    kind: str = "policy"

    def compile_for_cluster(self, cluster: Cluster) -> CompiledArtifact | None:
        if not cluster.records:
            return None
        if self.dsl == "cedar":
            body = _emit_cedar(cluster)
        elif self.dsl == "rego":
            body = _emit_rego(cluster)
        else:
            raise ValueError(f"Unsupported policy DSL: {self.dsl!r}")
        return CompiledArtifact(
            kind=self.kind,
            name=f"{self.dsl}-rule-cluster-{cluster.label}",
            payload=body,
            cluster_label=cluster.label,
            attack_success_rate=cluster.attack_success_rate,
            n_records=cluster.size,
            summary=cluster.summary,
            metadata={"dsl": self.dsl},
        )


def _emit_cedar(cluster: Cluster) -> str:
    sample = cluster.records[0].input[:80].replace('"', '\\"')
    return (
        f'// auto-generated by aisafepy.adapt from cluster {cluster.label}\n'
        f"// summary: {cluster.summary}\n"
        f'forbid (\n'
        f"    principal,\n"
        f"    action == Action::\"submitPrompt\",\n"
        f"    resource\n"
        f") when {{\n"
        f'    context.prompt like "*{sample}*"\n'
        f"}};\n"
    )


def _emit_rego(cluster: Cluster) -> str:
    sample = cluster.records[0].input[:80].replace('"', '\\"')
    return (
        f"# auto-generated by aisafepy.adapt from cluster {cluster.label}\n"
        f"package aisafepy.cluster_{cluster.label}\n\n"
        f"default deny = false\n\n"
        f"deny {{\n"
        f'    contains(input.prompt, "{sample}")\n'
        f"}}\n"
    )
